### ISSUE TITLE
64 bit version?

### ISSUE THREAD

**Issue by lossius** [AlexHarker/AHarker_Externals#1]
Thanks for the work you've been putting into this. I'm wondering if you have any idea about when/if you would be able to provide a 64-bit version of these externals?

Additionally it would be nice if they could be distributed as a Max 6.1/Max 7 style package.

Thanks!

**Comment by AlexHarker** [comment]
Hi Trond,

It’s in progress, but it is unfortunately hard to find time to work on this at the moment. I’m about halfway through, but unfortunately the half that is left is the more difficult half.
The next distro will be a package also as well as BSD licensed.

The end of the summer was a deadline I had in my head, but that is now done, so I really don’t know is the honest answer. As my dev time is research driven, and maintenance is not research it is hard to prioritise. I will need them at some point for composition stuff (that will accelerate the process), but other technical projects are dominating my research time right now. 

If you are super in a rush for specific things you could either let me know what they are, or take a look at the github which has all the source - in many cases it is a laborious checking of long / int variables that is needed, although there are a couple of cases of. In most cases mac builds are likely to work without alteration (but I can’t guarantee it), but the same is not the case for windows (I’ll finally do windows release at that point too).

Alex

**Comment by Mortimyrrh** [comment]
Hi Alex,

I know you have been busy with so much, but have there been any developments on an 64 bit distribution since the last post?

Mortimer

**Comment by AlexHarker** [comment]
If you don't need the descriptors objects then everything else should as far as I know build and work. I think on more modern Xcode's it will complain about 2 bit being unsupported, but let me see if I can fix that as a colleague has also been asking about that. So yes - it's further on than my last post, but not quite complete.

**Comment by AlexHarker** [comment]
Closing, as the main branch is now 64bit.
