### ISSUE TITLE
entrymatcher instacrash when double-clicking empty entrymatcher

### ISSUE THREAD

**Issue by rconstanzo** [AlexHarker/AHarker_Externals#11]
100% reproducable crash (on my system, details below) when double-clicking an "empty" `entrymatcher`. This happens if the object is named or unnamed, has size/columns or not.

Steps to reproduce:
instantiate `entrymatcher`, double-click it

This is with version "1.1" created on 19/07/2019 according to Finder.

Crash report:
[crash1.zip](https://github.com/AlexHarker/AHarker_Externals/files/5356537/crash1.zip)

**Comment by rconstanzo** [comment]
Correction, it appears to be crashing regardless.

I also forgot to add OS/Max info:

OSX 10.14.6
Max 8.1.6

**Comment by AlexHarker** [comment]
Regardless of what?

**Comment by rconstanzo** [comment]
Sorry, regardless of whether `entrymatcher` has data in it or not. Double-clicking the "1.1" build of `entrymatcher` on my system crashes Max.

**Comment by rconstanzo** [comment]
Don't know if this is the same crash or not, but on OSX 10.14.6 and Max 8.1.8:
[entrymatcher crash.zip](https://github.com/AlexHarker/AHarker_Externals/files/5747841/entrymatcher.crash.zip)

**Comment by AlexHarker** [comment]
Can you check with the currently alpha release on here (https://github.com/AlexHarker/AHarker_Externals/releases). If this is now solved please close.

**Comment by rconstanzo** [comment]
Looks good here.
