### ISSUE TITLE
can't build dynamicdsp~ on Windows

### ISSUE THREAD

**Issue by vensanmazmanyan** [AlexHarker/AHarker_Externals#12]
I wasn't able to build the external by following the provided readme file.
The VS solution references  a .c file which is not present.

**Comment by AlexHarker** [comment]
This should be fixed on the main (now default) branch. Please update me either way if possible, but I'll likely close this if I don't hear after a while as the repro has been fairly substantially revised and thus this is likely no longer relevant.

**Comment by AlexHarker** [comment]
Instructions now included, plus alpha windows builds
