### ISSUE TITLE
Can't build projects depending on AH_VectorOps.h

### ISSUE THREAD

**Issue by andreaagostini** [AlexHarker/AHarker_Externals#13]
Hi Alex,
I'm trying to build your externals in XCode and I get this:
AH_VectorOps.h:387
Constant expression evaluates to 9223372036854775808 which cannot be narrowed to type 'long long'.
No big deal for now as I don't need the descriptors object, but I wanted to let you know. This happens on Mac OSX 10.13.6, XCode 9.4.1, building against the Max SDK 7.3.3.
Take care,
andrea

**Comment by kylemcdonald** [comment]
Hi, I have a fix for this in another issue (I think) https://github.com/AlexHarker/AHarker_Externals/issues/15#issue-931013096

**Comment by AlexHarker** [comment]
I think this will disappear when the header does. For some reason the public versions are quite behind my local repo, but I don't yet have time to look into this in much detail.

**Comment by AlexHarker** [comment]
No longer an issue on the default branch (where the file structure has significantly changed)
