### ISSUE TITLE
compile failing

### ISSUE THREAD

**Issue by tremblap** [AlexHarker/AHarker_Externals#14]
At the moment I get this error when I load in Catalina's Xcode (12.2)
![Screenshot 2021-04-06 at 16 57 24](https://user-images.githubusercontent.com/10000381/113741471-98d43800-96f9-11eb-9d79-7ff198b5f548.jpg)

and when I try to compile anyway I get 88 errors:
Error Group
The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture.

I presume there is a way to go and edit stuff but I prefer to point and moan.

**Comment by AlexHarker** [comment]
Config_AHarker_Externals.xcconfig line 33...

Remove i386

There is no way to branch for this based on Xcode version (which is what it depends on), unfortunately.

**Comment by tremblap** [comment]
ok, changed that, and read the read me.

- the name of the folders to copy/link the c74support folder is not right and needs updating

once that is updated it finds everything except these 8:

vrdiv~ Group
Error Group
Build input file cannot be found: '/Volumes/machins/essai_C/externals/AHarker_Externals/vMSP/vMSP/../../AH_Max_SDK/c74support/max-includes/macho-prefix.pch'
timefilter Group
Error Group
Build input file cannot be found: '/Volumes/machins/essai_C/externals/AHarker_Externals/gesture suite/timefilter/../../AH_Max_SDK/c74support/max-includes/macho-prefix.pch'
vtimes~ Group
Error Group
Build input file cannot be found: '/Volumes/machins/essai_C/externals/AHarker_Externals/vMSP/vMSP/../../AH_Max_SDK/c74support/max-includes/macho-prefix.pch'
vsinx~ Group
Error Group
Build input file cannot be found: '/Volumes/machins/essai_C/externals/AHarker_Externals/vMSP/vMSP/../../AH_Max_SDK/c74support/max-includes/macho-prefix.pch'
timeconvolve~ Group
Error Group
Build input file cannot be found: '/Volumes/machins/essai_C/externals/AHarker_Externals/convolution/timeconvolve~/../../AH_Max_SDK/c74support/max-includes/macho-prefix.pch'
vtrunc~ Group
Error Group
Build input file cannot be found: '/Volumes/machins/essai_C/externals/AHarker_Externals/vMSP/vMSP/../../AH_Max_SDK/c74support/max-includes/macho-prefix.pch'
voicemanager~ Group
Error Group
Build input file cannot be found: '/Volumes/machins/essai_C/externals/AHarker_Externals/sample accurate suite/voicemanager~/../../AH_Max_SDK/c74support/max-includes/macho-prefix.pch'
timemap Group
Error Group
Build input file cannot be found: '/Volumes/machins/essai_C/externals/AHarker_Externals/gesture suite/timemap/../../AH_Max_SDK/c74support/max-includes/macho-prefix.pch'

**Comment by AlexHarker** [comment]
I checked a few of the above and the location is defined in the config file for all I checked. I recommend clean and build again, as I don't see an issue here.

I will update the getting started when I can.

**Comment by tremblap** [comment]
I did clean many times, like a good student. to no avail. I can see the files indeed, but maybe the link I put is not good... I will try making a symlink in the terminal instead...

**Comment by tremblap** [comment]
that did the trick, but we now have a new pair of errors:

Semantic Issue Group
/Volumes/machins/essai_C/externals/AHarker_Externals/AH_MaxMSP_Headers/AH_VectorOps.h:387:42: Constant expression evaluates to 9223372036854775808 which cannot be narrowed to type 'long long'
/Volumes/machins/essai_C/externals/AHarker_Externals/descriptors/descriptors~/descriptors_per_frame_descriptors.cpp:17:10: In file included from /Volumes/machins/essai_C/externals/AHarker_Externals/descriptors/descriptors~/descriptors_per_frame_descriptors.cpp:17:
/Volumes/machins/essai_C/externals/AHarker_Externals/descriptors/descriptors~/descriptors_per_frame_descriptors.h:17:10: In file included from /Volumes/machins/essai_C/externals/AHarker_Externals/descriptors/descriptors~/descriptors_per_frame_descriptors.h:17:
/Volumes/machins/essai_C/externals/AHarker_Externals/AH_MaxMSP_Headers/AH_VectorOps.h:387:42: Insert an explicit cast to silence this issue
/Volumes/machins/essai_C/externals/AHarker_Externals/AH_MaxMSP_Headers/AH_VectorOps.h:387:62: Constant expression evaluates to 9223372036854775808 which cannot be narrowed to type 'long long'
/Volumes/machins/essai_C/externals/AHarker_Externals/descriptors/descriptors~/descriptors_per_frame_descriptors.cpp:17:10: In file included from /Volumes/machins/essai_C/externals/AHarker_Externals/descriptors/descriptors~/descriptors_per_frame_descriptors.cpp:17:
/Volumes/machins/essai_C/externals/AHarker_Externals/descriptors/descriptors~/descriptors_per_frame_descriptors.h:17:10: In file included from /Volumes/machins/essai_C/externals/AHarker_Externals/descriptors/descriptors~/descriptors_per_frame_descriptors.h:17:
/Volumes/machins/essai_C/externals/AHarker_Externals/AH_MaxMSP_Headers/AH_VectorOps.h:387:62: Insert an explicit cast to silence this issue

**Comment by AlexHarker** [comment]
This will take a while to look into, because by local repo is further ahead than the public one, so it's not easy to investigate all of this, but it's possible commenting out the offending functions entirely will solve it.

**Comment by tremblap** [comment]
No problem, just write here when a new version is pushed so I can try it.

**Comment by AlexHarker** [comment]
I can do, but I have no guarantee as to when that will be at the moment.

**Comment by AlexHarker** [comment]
No longer an issue on the default branch (where the file structure has significantly changed)
