### ISSUE TITLE
ibuffer~ help file crashes on Win11 64bit as soon as the dac~ is turned on

### ISSUE THREAD

**Issue by alfonso73** [AlexHarker/AHarker_Externals#17]
Very happy that Win version fo your external are coming @AlexHarker !
Thanks.
Just found a bug i reported in the issue title.
ibuffer~ help file crashes on Win11 64bit as soon as the dac~ is turned on.
I'm on latest Max 8.3.2

**Comment by AlexHarker** [comment]
Thanks - I'll test - in the meantime if you have any kind of crash report (if available) that might help.

It won't be the ibuffer~ object itself. Do the ibufplayer~ / ibuftable~ help files work?

**Comment by AlexHarker** [comment]
Also - can you confirm the version you are testing with (which release, or if you built at your end).

**Comment by alfonso73** [comment]
Hi @AlexHarker, i'm using this release https://github.com/AlexHarker/AHarker_Externals/releases/tag/latest-2022-07-30
I go test ibufplayer~ / ibuftable~ in a while and report back

**Comment by alfonso73** [comment]
The culprit seems to be ibufplayer~ .
As soon as I activate dac~ in ibufplayer~ help file Max just crashes and quits.
Everything seems to be fine with ibuftable~

**Comment by AlexHarker** [comment]
OK - I know why this is happening, and hope to fix it soon - it's really pretty straightforward, but I need to check a few similar objects and make the solution consistent.

**Comment by AlexHarker** [comment]
Should be fixed in https://github.com/AlexHarker/AHarker_Externals/releases/tag/latest-2022-09-19 

@alfonso73 - can you give it a quick spin to check?

**Comment by alfonso73** [comment]
Seems to be error free now! thanks

**Comment by AlexHarker** [comment]
Great!
