### ISSUE TITLE
partconvolve~ sounding completely broken on Apple Silicon

### ISSUE THREAD

**Issue by v7b1** [AlexHarker/AHarker_Externals#19]
Hi Alex, 
happy to see these externals being updated to Apple Silicon now, thanks great!
Just tried out the zero_latency_convolution_demo.maxpat patch on my M1 machine and unfortunately the output sounds completely broken. Chopped up audio and amplitudes completely out or range, like reading garbage memory - quite interesting actually, but not much reverb-like... I think the problem is with [partconvolve~]. 
[timeconvolve~] seems to work fine.
I'm testing on macos 12.4 and Max 8.5.1
best, volker

**Comment by AlexHarker** [comment]
Thanks for the report. The good (or bad) news depending on your view is that it is also broken on intel. This is actually preferable to me, as I'm away from my M1 machine - I'll try to fix that up as soon as I can.

In general I'd advise multiconvolve~ from the HIRT package for this kind of convolution these days, but this object should still work....

**Comment by AlexHarker** [comment]
I have a point when this wasn't happening and the Apple Silicon work was done, so I should be able to trace it fairly quickly...

**Comment by AlexHarker** [comment]
OK - it was a typical one-liner stupidity in a "tidying" commit back on Feb 2nd.

It should be fixed by 57451bffe85f400718d2b3e2d0be61bd4cebaf0f.

@v7b1 - can you test with the new builds once they've completed (probably about 25 mins from now) and confirm that this is fixed? Thanks for the catch!
