### ISSUE TITLE
dynamicdsp~ and efficiency vs performance cores

### ISSUE THREAD

**Issue by HansElectrumpet** [AlexHarker/AHarker_Externals#22]
Hi Alex,

I hope you are doing well!!!

You have advised in the past to not assign specific cores and to use automatic load balancing when using dynamicdsp~. I have recently acquired a M2 max machine and I was wondering if that advice is still valid with these or that specific assignment of heavy processing tasks to performance cores can be a good strategy nowadays or perhaps you have some notable insight into other quirks that are good to know when using these new processors in relation to threading and your objects.

Best, Hans.

**Comment by AlexHarker** [comment]
Sorry for the delay on this. The advise is still valid - autoloadbalance is best (and in the new versions is an attribute, so you should be able to set this by default).
