### ISSUE TITLE
Request for a build with AVX disabled

### ISSUE THREAD

**Issue by alexanderpanos** [AlexHarker/AHarker_Externals#35]
When a host program (such as Ableton Live) is run in Rosetta, the externals crash that host program. I am requesting a build with the AVX instructions disabled so the externals are able to run within Rosetta.

Thank you!

**Comment by AlexHarker** [comment]
Please try:

https://github.com/AlexHarker/AHarker_Externals/releases/tag/latest-sse-2023-11-14
