### ISSUE TITLE
descriptorsrt~ stops outputting

### ISSUE THREAD

**Issue by AlexHarker** [AlexHarker/AHarker_Externals#5]
From Rod:

ok so gave it a good test today while filming and stuff, and I can confirm that your build doesn't blow up the scheduler when left for a long time.

that being said, one of the issues still persists, where after a certain amount of time, one of the (several) descriptorsrt~ stops sending messages...
I was using a hacky workaround as a safety net at the gig where connecting/disconnecting a bang object to the outlet would kick start the output, but for whatever reason (having changed nothing else), that now turns OFF the dac for a split second, causing an audio dropout (like when you connect/disconnect an audio cable).

The weird thing is that the scheduler is still running, with UI elements still working and everything, so it appears to be a completely different (yet similar) problem, isolated to just this one object (as i mentioned, among many).

I've managed to get a take or two where this part of the patch was working, but it falls smack in the middle of a 9min thing, and its a dice roll whether its still working by the time i get there (without the hacky audio disconnection)

Is there another (equally hacky?) way, to kick start the scheduler without interrupting audio?
Running in audio interrupt works, but it gets a bit crunch running this patch at 64/32 vector size (for feedback purposes)

This is the big of audio in question (the abstraction that's missing is a generic audio gate)

<pre><code>
----------begin_max5_patcher----------
1543.3ocyY0zbahCF9ryuBFe1wi9Vvdp6tG5kcm8POryNc1ICFjcnECdDh1j
sSyu88UR.FbrcLIjz5CDgfWzidd+Tu4aWMa9px6TUyC9kfOFLa12tZ1L2T1I
l0b+r4aiuKIOtx8ZyKTesb0mluv+Hi5Nia5cwIeNXc.G09jh5sk0lbkwIFtY
V+Tl62o7q474A+ayixRceH3iecHt8qTYtO28pyamYWrI41rhM2nUIF+GAS3h
knEALNy9Gdj8JgrD08sAvjUzhEhctue0U1KKdY657rBU.Z4w2yjStmWbp8M5
4sui3t+PO+9l9L12aqyMYU4YoJcKPVsIoLuT6g.ZIIBgiDKfQTTTHh4GASgW
Df6AkRclpvDaxJKrhhNKkkDWjlAWTj1kIDQiHD6GOLxN1NJpYAGrLmmrqfEp
kZw6mCXIXa6k3ZLCYIRTuuZOcDP5iSIwvg.lAzaIDAfUtDvML1po.8kn253Y
5A76ktwGnpwc3QGuUYT5aTEwq7fEMcl+6Jyu+gfc5xDUU0MahMpGBdm1piAP
F7NysZU0sAWys2DaL1PDbXXpJI99.hc1aKySCvH6vsweVUuKfz4MYctRJqKL
8sLFZuPOkVuJaSQbtU2uezQc4v3w5yI3K4gTBGzIXjboThoBXLEispSJ+MHr
Shtrp5AHXKZjQddDsbLJQNRBAy5HDgbIKjK3xEARzaVTXyICAexzNqyKiMGc
2SFo8.Es2dfBaWbTTDGb0Ixyu+wS29uZWdlkCf3AizdvSCKNKefe99GjP7xH
LivDOcVY5DlUtLNcUbwlQZS3D4nT.cjTPzdOh9Q7Eno2jXKD4Mdi5Qbv50FW
v+JHHEgEvw.VRUUI5rclRcUP05sAgHDDEFgljZ1Xu.RhfvKoLhTRs4CIu1AN
9Rrt.RK5dhUouu1lN5qGUoMOLR9IOq539RL9KvWhgWJHgbHseH6xsibugKU5
AU46VO67CospxZcR6FosV7f8KDPLlrhtx3939BW68R2lklpFTlWZVks9iz9y
UpsUUdR69KEfP5p.7SfOWV9KGfuH7XUxOIgQv+3HLqm5SBvC1EulDF4hvC8s
COWjEO9sEOOkEN4sy.+fk5GN+bny8ObCZOfHOULIBephA3CxGua2WT5plUwg
NHK3m7GkTtvcaVg+V2AmlqUeIq888yDqgjPFHCTs1md5tPwbunkvBWTm0r1.
ubUSZrCRrzkZ8WqSyJ+.bj+5pa9SUQsOSGvFqiqyMC4vUaVmkm2cv2YcOAxI
2jXct+oKZl9flPvv3PWqGvTIw2NBX.m2yyoQFbqPLNKB4NYMSPjLtaTHgxoC
N7eiXjQ1vCfKK13ywSbmEpYV3zx6J0csAYIbh912u1TtQGmZ6SRmQnWE6oa+
A5gmdX0C91zzJSeS1NkweTmDedEv.BMBwvxHeWG3LozMhQhjNVhK5rZGHESx
wT2aPhnfftQbLRDMrWEwIIvtXfnPQNL25QYbWwxvHoet9RpxUaOTTYnP3wUH
BGF5GAeEaWS5KaEHbhk3GJMAfma8vBIwq5gBiwGzdEakgN4tIqv5ko5LGrc1
Q32os1SDYHidP+uVWVXZ0FPDf+ZmpH3CwEUAePsMaUYd59JFuDmgNCkS3Obg
1nC8HB67CBkHdXnezi1KG5QHZ0XB6Ooej+K8yqCwm88Z6usg6NmiQOd00fmA
WB92IAKvYUD1Cvbo9mG.Dvg7btVd0XmYp7HMO7jV299f1bYZ2vtyqbgLODZA
hKSh5GVv5lw33oFVCNP8wA1HXqWrGcOeyVeqGO5L9lxPaFsEGcziE6mxbbC8
NtLsn+L4Wr0kSm0qdflNsOcVV9FP7a40pqwmCUGKyHVJX9fpc.LxNE9U.f5x
uVLZDtGW7NeS5qDB+86iGO.QDnHFevOIkR79NDLFSmd.9dsR8LPni8n1e9RQ
rohmdv8Op77xuddzYKToJ6+Ts8fZIhGgPgmMCCTjmzGYAGhcw+3.iymzMP81
UJ86gBkFM4ZMEQN0OGRBxcHE2OZ1j.PsufBKBGQg1OI1NVc1BlP3+OABVwxl
pyA9N54aOCx78q9e.lOQMp.
-----------end_max5_patcher-----------
</code></pre>

**Comment by rconstanzo** [comment]
This looks alright, and I can't reproduce.

**Comment by AlexHarker** [comment]
Can I close?

**Comment by rconstanzo** [comment]
Yup, it didn't give me the option since I didn't create the issue on github. Close away!
