### ISSUE TITLE
entrymatcher~ jdataview zeroing out values

### ISSUE THREAD

**Issue by rconstanzo** [AlexHarker/AHarker_Externals#7]
At the moment if you double-click the object and are looking at the spreadsheet view, and you (single) click on any of the fields, it zeros out that field.

Double-clicking it zeros it out and selects the field (which seems like expected-ish behavior), but having a single click do it feels a bit severe.

Also it feels like the expected behavior here would be single click = nothing happens, it just selects the field, and a double-click selects the existing entry, which can then be edited (or zeroed out).

<img width="164" alt="Screen Shot 2019-09-23 at 10 40 36 pm" src="https://user-images.githubusercontent.com/2747015/65492035-1e8deb00-dea8-11e9-8c93-250ab9f4aa0a.png">

**Comment by AlexHarker** [comment]
This only happens in Max8, and is to do with the difference between jdataview handling in the two versions of Max.

**Comment by AlexHarker** [comment]
Can you check with the currently alpha release on here (https://github.com/AlexHarker/AHarker_Externals/releases). If this is now solved please close.

**Comment by rconstanzo** [comment]
Looks good here.
